apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: testazurenodejs0613 
  janus-idp.io/tekton: testazurenodejs0613
  backstage.io/kubernetes-id: testazurenodejs0613
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: testazurenodejs0613
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml