apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testazurenodejs0613
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testazurenodejs0613 
  name: testazurenodejs0613
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: testazurenodejs0613 
